import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { stringify } from "yaml";

import type { ResolvedConfig } from "../core/config/types.ts";
import type { Language } from "../core/config/schema.ts";

export const CALLER_WORKFLOW = `name: quality
on: [pull_request, push]
permissions: { contents: read, packages: read }
jobs:
  quality:
    uses: Runroom/code-quality/.github/workflows/quality.yml@v1
`;

export const MAKEFILE_SNIPPET = `quality:
\tdocker run --rm -v "$$PWD:/work" ghcr.io/runroom/code-quality:v1 check

quality-baseline:
\tdocker run --rm -v "$$PWD:/work" ghcr.io/runroom/code-quality:v1 baseline
`;

function configPaths(config: ResolvedConfig): Partial<Record<Language, string[]>> {
  const paths: Partial<Record<Language, string[]>> = {};
  for (const language of config.languages) {
    paths[language] = config.paths[language] ?? [];
  }
  return paths;
}

export function renderConsumerConfig(config: ResolvedConfig): string {
  const content = stringify({ languages: config.languages, paths: configPaths(config) });
  return `# Generated by code-quality init. Review these languages and paths.\n${content}`;
}

function writeMissing(root: string, relative: string, content: string): void {
  const file = join(root, relative);
  if (!existsSync(file)) writeFileSync(file, content, "utf8");
}

function writeWorkflow(root: string): void {
  const directory = join(root, ".github", "workflows");
  mkdirSync(directory, { recursive: true });
  writeMissing(root, ".github/workflows/quality.yml", CALLER_WORKFLOW);
}

function writeMakefile(root: string, log: (value: string) => void): void {
  if (existsSync(join(root, "Makefile"))) {
    log(MAKEFILE_SNIPPET);
    return;
  }
  writeFileSync(join(root, "Makefile"), MAKEFILE_SNIPPET, "utf8");
}

export function scaffold(root: string, config: ResolvedConfig, log: (value: string) => void): void {
  writeMissing(root, ".code-quality.yml", renderConsumerConfig(config));
  mkdirSync(join(root, "quality"), { recursive: true });
  writeWorkflow(root);
  writeMakefile(root, log);
}
