import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { stringify } from "yaml";

import type { ResolvedConfig } from "../core/config/types.ts";
import type { Language } from "../core/config/schema.ts";

export const CALLER_WORKFLOW = `name: quality
on: [pull_request, push]
permissions: { contents: read, packages: read }
jobs:
  quality:
    uses: Runroom/code-quality/.github/workflows/quality.yml@v1
`;

export const MAKEFILE_SNIPPET = `# code-quality — run these through make; \`$$PWD\` is Make escaping for \`$PWD\`
CODE_QUALITY_IMAGE ?= ghcr.io/runroom/code-quality:v1
# Must be a single image reference; it is interpolated into docker run unquoted.
CODE_QUALITY = docker run --rm -v "$$PWD:/work" $(CODE_QUALITY_IMAGE)

.PHONY: quality quality-all quality-baseline quality-report quality-doctor

quality:
	$(CODE_QUALITY) check

quality-all:
	$(CODE_QUALITY) check --all

quality-baseline:
	$(CODE_QUALITY) baseline

quality-report:
	$(CODE_QUALITY) report

quality-doctor:
	$(CODE_QUALITY) doctor
`;

const QUALITY_GITIGNORE_ENTRIES = ["artifacts/quality/"] as const;
const QUALITY_GITIGNORE_COMMENT = "# code-quality";
const MAKEFILE_NAMES = ["GNUmakefile", "makefile", "Makefile"] as const;
const CODE_QUALITY_ASSIGNMENT = /^[ \t]*(?:export[ \t]+|override[ \t]+)?CODE_QUALITY[ \t]*(?::::?|[:?+!])?=/m;
const QUALITY_TARGET = /^[ \t]*quality(?:-all|-baseline|-report|-doctor)?[ \t]*::?/m;
const PHONY_QUALITY_TARGET = /^[ \t]*\.PHONY[ \t]*:.*(?<![\w-])quality(?:-all|-baseline|-report|-doctor)?(?![\w-])/m;
const RECIPE_PREFIX = /^[ \t]*\.RECIPEPREFIX\b/m;

function configPaths(config: ResolvedConfig): Partial<Record<Language, string[]>> {
  const paths: Partial<Record<Language, string[]>> = {};
  for (const language of config.languages) {
    paths[language] = config.paths[language] ?? [];
  }
  return paths;
}

export function renderConsumerConfig(config: ResolvedConfig): string {
  const content = config.languages.length === 0
    ? stringify({})
    : stringify({ languages: config.languages, paths: configPaths(config) });
  return `# Generated by code-quality init. Review these languages and paths.\n${content}`;
}

function writeMissing(root: string, relative: string, content: string): void {
  const file = join(root, relative);
  if (!existsSync(file)) writeFileSync(file, content, "utf8");
}

function writeWorkflow(root: string): void {
  const directory = join(root, ".github", "workflows");
  mkdirSync(directory, { recursive: true });
  writeMissing(root, ".github/workflows/quality.yml", CALLER_WORKFLOW);
}

function resolveMakefile(root: string): { name: typeof MAKEFILE_NAMES[number]; path: string } | undefined {
  const entries = readdirSync(root);
  const name = MAKEFILE_NAMES.find((candidate) => entries.includes(candidate));
  return name === undefined ? undefined : { name, path: join(root, name) };
}

function hasQualityTarget(content: string): boolean {
  return QUALITY_TARGET.test(content) || PHONY_QUALITY_TARGET.test(content);
}

function spaceIndentedRecipeLine(content: string): number | undefined {
  const lines = content.split(/\r?\n/);
  for (let index = 0; index < lines.length - 1; index += 1) {
    if (QUALITY_TARGET.test(lines[index] ?? "") && /^ +[^\s#]/.test(lines[index + 1] ?? "")) {
      return index + 2;
    }
  }
  return undefined;
}

function readMakefile(
  resolved: { name: typeof MAKEFILE_NAMES[number]; path: string },
  log: (value: string) => void,
): string | undefined {
  try {
    return readFileSync(resolved.path, "utf8");
  } catch (error) {
    const code = error instanceof Error && "code" in error ? error.code : "unknown";
    log(`Kept ${resolved.name}: could not read it (${code})`);
    return undefined;
  }
}

function keepExistingMakefile(
  name: typeof MAKEFILE_NAMES[number],
  existing: string,
  log: (value: string) => void,
): boolean {
  if (CODE_QUALITY_ASSIGNMENT.test(existing)) {
    const line = spaceIndentedRecipeLine(existing);
    if (line !== undefined) {
      log(`Kept ${name}: quality recipes at line ${line} are indented with spaces; Make needs a tab (fix: replace the leading spaces with one tab).`);
    } else {
      log(`Kept ${name}`);
    }
    return true;
  }
  if (hasQualityTarget(existing) || RECIPE_PREFIX.test(existing)) {
    log(`Kept ${name}: it already defines a quality target or a custom recipe prefix. Add these targets by hand; recipe lines must start with a tab:`);
    log(MAKEFILE_SNIPPET);
    return true;
  }
  return false;
}

function makefilePrefix(existing: string, newline: string): string {
  return existing.length === 0
    ? ""
    : existing.endsWith(newline + newline)
      ? ""
      : existing.endsWith("\n")
        ? newline
        : newline + newline;
}

function writeMakefile(root: string, log: (value: string) => void): void {
  const resolved = resolveMakefile(root);
  if (resolved === undefined) {
    writeFileSync(join(root, "Makefile"), MAKEFILE_SNIPPET, "utf8");
    log("Created Makefile (make quality)");
    return;
  }

  const existing = readMakefile(resolved, log);
  if (existing === undefined || keepExistingMakefile(resolved.name, existing, log)) return;

  const newline = existing.includes("\r\n") ? "\r\n" : "\n";
  const snippet = MAKEFILE_SNIPPET.replaceAll("\n", newline);
  writeFileSync(resolved.path, `${existing}${makefilePrefix(existing, newline)}${snippet}`, "utf8");
  log(`Updated ${resolved.name} (make quality)`);
}

function writeGitignore(root: string, log: (value: string) => void): void {
  const file = join(root, ".gitignore");
  if (!existsSync(file)) {
    writeFileSync(
      file,
      `${QUALITY_GITIGNORE_COMMENT}\n${QUALITY_GITIGNORE_ENTRIES.join("\n")}\n`,
      "utf8",
    );
    log("Updated .gitignore (artifacts/quality/)");
    return;
  }

  const existing = readFileSync(file, "utf8");
  const existingLines = existing.split(/\r?\n/);
  const missing = QUALITY_GITIGNORE_ENTRIES.filter((entry) => !existingLines.includes(entry));
  if (missing.length === 0) {
    log("Kept .gitignore");
    return;
  }

  const newline = existing.includes("\r\n") ? "\r\n" : "\n";
  const separator = existing.length === 0 || existing.endsWith("\n") ? "" : newline;
  writeFileSync(
    file,
    `${existing}${separator}${QUALITY_GITIGNORE_COMMENT}${newline}${missing.join(newline)}${newline}`,
    "utf8",
  );
  log("Updated .gitignore (artifacts/quality/)");
}

export function scaffold(root: string, config: ResolvedConfig, log: (value: string) => void): void {
  writeMissing(root, ".code-quality.yml", renderConsumerConfig(config));
  mkdirSync(join(root, "quality"), { recursive: true });
  writeWorkflow(root);
  writeMakefile(root, log);
  writeGitignore(root, log);
}
